var inputLessonItems = [{
    name: "Keyboard",
    description: "A keyboard is used to enter data into a computer or other device.",
    imageSource: "img/keyboard-int.jpg",
    full_description: {firstp:"Similar to an electric typewriter, a keyboard is composed of buttons that create letters, numbers, and symbols, as well as perform other functions. A keyboard uses labeled buttons as input switches.",secondp:"The standard QWERTY keyboard is the commonest way to enter text and numerical data into a computer. A keyboard uses labeled buttons as input switches. The standard QWERTY keyboard is the commonest way to enter text and numerical data into a computer. Alternatives to fixed layouts include overlay keyboards and touch screen keyboards, both allowing easy customization.", thirdp:"• Suited to: Entering text and number data into a computer system. Making selections on devices.• Advantages: Reliable for data input of text and numbers. Usually supplied with a computer so no additional cost. Specialized keyboards are available for particular purposes.• Disadvantages: Slow to enter data and prone to typographical errors with new users. Slow for accessing menus etc. and difficult to use if you want to move objects around the screen. Difficult for users unable to use a keyboard through paralysis or muscular disorder."},
    images: [{image: "img/input/Keyboard/1.jpg",name:"Flexible Keyboard",caption: "are basically a blend between standard and laptop keyboards in both functionality and purpose. A typical flexible keyboard features both large number of keys and short key distance."},
    {image:"img/input/Keyboard/2.jpg",name:"Gaming Keyboard",caption: "A dedicated gaming keyboard is much like a standard keyboard except they have a few additional features such as multimedia keys, LED screen and palm rest."},
    {image: "img/input/Keyboard/3.jpg", name:"Ergonomic Keyboard",caption: "An ergonomic keyboard is a computer keyboard designed with ergonomic considerations to minimize muscle strain and a host of related problems."}]
},

{
    name: "Mouse",
    description: "A mouse is a device that controls the movement of the cursor or pointer on a display screen.",
    imageSource: "img/mouse-int.jpg",
    full_description: {firstp:"The mouse is used to control the movement of a pointer on the screen when it is moved horizontally over a flat surface. Buttons on the mouse let you select options from menus and drag objects around the screen etc.",secondp:"A computer mouse is a handheld hardware input device that controls a cursor in a GUI and can move and select text, icons, files, and folders. For desktop computers, the mouse is placed on a flat surface such as a mouse pad or a desk and is placed in front of your computer. The pictures provided at the top are examples of a desktop computer mouse with two buttons and a wheel.", thirdp:"• Suited to: A graphical user interface where pointing with a screen pointer is combined with selection using buttons to access items / menus / hyperlinks etc.   •Advantages: Ideal for use with desktop computers. Usually supplied with a computer so no additional cost. All computer users tend to be familiar with using them.                    • Disadvantages: They need a flat space close to the computer. The mouse cannot easily be used with laptop, notebook or palmtop computers when not near a flat surface (these need a tracker ball or a touch sensitive pad called a touch pad)."},
    images: [{image:"img/input/Mouse/1.jpg", name:"Wireless Mouse" ,caption:"The Mouse without wire or cord is called wireless mouse or cordless mouse. Most wireless mice use radiofrequency (RF) technology to communicate information to your computer."},
    {image:"img/input/Mouse/2.jpg", name:"GStick Mouse",caption:"This mouse is wireless and pocket-sized. It looks like a pencil and it can be used for web browsing, office work or whatever you do with your traditional mouse, with more comfort"},
    {image:"img/input/Mouse/3.jpg",name:"Optical Mouse", caption:"An optical mouse is an computer pointing device that uses a light-emitting diode an optical sensor, and digital signal processing ( DSP ).This mouse doesn’t have mouse ball and electromechanical transducer. "}]
},
{
    name: "Camera",
    description: "A digital camera stores images digitally rather than recording them on film.",
    imageSource: "img/camera-int.jpg",
    full_description:{firstp:"A camera is a hardware device that takes photographs and consists of a lightproof box with photosensitive film or plate in the box.  A camera consists of a lens which focuses light from the scene, and a camera body which holds the image capture mechanism. ",secondp:"When a picture is taken, the camera's shutter opens and closes, exposing the photosensitive film with light recording the image onto the film. Still images stored in digital form are called image files, while moving images similarly stored are called video files. In the deprecated paradigm of photographic film for image storage, still images are simply called photographs, and moving images are called films. The still image camera is the main instrument in the art of photography and captured images may be reproduced later as a part of the process of photography, digital imaging, photographic printing. The similar artistic fields in the moving image camera domain are film, videography, and cinematography.", thirdp:"Traditional cameras capture light onto photographic plate or photographic film. Video and digital cameras use an electronic image sensor, usually a charge coupled device (CCD) or a CMOS sensor to capture images which can be transferred or stored in a memory card or other storage inside the camera for later playback or processing. The lens of a camera captures the light from the subject and brings it to a focus on the sensor. The design and manufacture of the lens is critical to the quality of the photograph being taken. The technological revolution in camera design in the 19th century revolutionized optical glass manufacture and lens design with great benefits for modern lens manufacture in a wide range of optical instruments from reading glasses to microscopes."},
    images: [{image:"img/input/Camera/1.jpg", name:"Analog electronic camera", caption:"Recorded pixel signals continuously, as videotape machines did, without converting them to discrete levels"},
    {image:"img/input/Camera/2.jpg", name:"Digital Camera",caption:"Digital and movie cameras share an optical system, typically using a lens with a variable diaphragm to focus light onto an image pickup device."}]
},
{
    name: "Joystick",
    description: "A joystick is a peripheral device designed to be connected to a computer or console gaming system.",
    imageSource: "img/controller.jpg",
    full_description:{firstp:"A joystick is an input device commonly used to control video games. Joysticks consist of a base and a stick that can be moved in any direction. The stick can be moved slowly or quickly and in different amounts.",secondp:"•	Joysticks typically include several buttons as well. Most joysticks have at least one button on the top of the stick and another button in the front of the stick for the trigger. Many joysticks also include other buttons on the base that can be pressed using the hand that is not guiding the stick. Joysticks typically connect to your computer using a basic USB or serial port connection and often come with software that allows you to assign the function of each button.", thirdp:"• Since joysticks emulate the controls of planes and other aircraft, they are best suited for flight simulators and flying action games. However, some gamers like to use joysticks for other types of video games, such as first-person shooters and fighting games. Others prefer using the basic keyboard and mouse, with which they are already accustomed to. Used for video games, flight simulators, training simulators and for controlling industrial robots. "},
    images: [{image:"img/input/Game Controller/1.jpg",name:"Joystick",caption:"Joysticks consist of a base and a stick that can be moved in any direction. The stick can be moved slowly or quickly and in different amounts."},
    {image:"img/input/Game Controller/2.jpg",name:"Game Controller",caption:""}]
},
{
    name: "Scanner",
    description: "The scanner is used to store photographs, picture, and diagrams into the computer. It saves the image in the form of a file by reading it.",
    imageSource: "img/scanner.jpg",
    full_description: {firstp:"A scanner may be used to convert a printed picture, drawing, or document (hard copy) into a digital file which can be edited on a computer.",secondp: "Scanners come in hand-held, feed-in, and flatbed types and for scanning black-and-white only, or color. Very high resolution scanners are used for scanning for high-resolution printing, but lower resolution scanners are adequate for capturing images for computer display. Scanners usually come with software, such as Adobe's Photoshop product, that lets you resize and otherwise modify a captured image.", thirdp:"Modern scanners typically use a charge-coupled device (CCD) or a contact image sensor (CIS) as the image sensor, whereas drum scanners, developed earlier and still used for the highest possible image quality, use a photomultiplier tube (PMT) as the image sensor. A rotary scanner, used for high-speed document scanning, is a type of drum scanner that uses a CCD array instead of a photomultiplier. Non-contact planetary scanners essentially photograph delicate books and documents. All these scanners produce two-dimensional images of subjects that are usually flat, but sometimes solid; 3D scanners produce information on the three-dimensional structure of solid objects."},
    images: [{image:"img/input/Scanner/1.jpg",name:"Flatbed",caption:"A flatbed scanner is made up of a glass pane and a moving optical CIS or CCD array. The pane is illuminated with the help of bright light planted underneath it. The image―the one that is to be scanned―is then placed on the glass pane. The sensor and source of light move across the glass pane to scan the document and produce its digital copy."},
    {image:"img/input/Scanner/2.jpg",name:"Handheld",caption:"A handheld scanner is a small manual scanning device which is moved over the object that needs to be scanned. In flatback and sheetfed scanners, you put the document that is to be scanned inside the device. In contrast, in the case of heldheld scanner, you have to drag it over the document that is to be scanned. "},
    {image:"img/input/Scanner/3.jpg",name:"Sheetfed",caption:". The prominent components of a sheetfed scanner include the sheet-feeder, scanning module, and calibration sheet. While the sensor and source of light move across the glass pane in flatbed scanners, in sheetfed scanners, they are stationary."}]

},
{
    name: "Graphics Tablet",
    description: "A graphics tablet is a hardware input device that enables an artist to draw or sketch digitally using a pen or stylus.",
    imageSource: "img/tablet.jpg",
    full_description: {firstp:"A graphics tablet is a hardware input device that enables an artist to draw or sketch digitally using a pen or stylus. They are helpful because they provide a more natural and precise feel than a standard computer mouse.",secondp:"These tablets may also be used to capture data or handwritten signatures. It can also be used to trace an image from a piece of paper which is taped or otherwise secured to the tablet surface. Capturing data in this way, by tracing or entering the corners of linear poly-lines or shapes, is called digitizing.The device consists of a flat surface upon which the user may draw or trace an image using the attached stylus, a pen-like drawing apparatus. The image is displayed on the computer monitor, though some graphic tablets now also incorporate an LCD screen for a more realistic or natural experience and usability.Some tablets are intended as a replacement for the computer mouse as the primary pointing and navigation device for desktop computers.", thirdp:"Graphic tablets, because of their stylus-based interface and ability to detect some or all of pressure, tilt, and other attributes of the stylus and its interaction with the tablet, are widely considered to offer a very natural way to create computer graphics, especially two-dimensional computer graphics. Indeed, many graphic packages can make use of the pressure (and, sometimes, stylus tilt or rotation) information generated by a tablet, by modifying the brush size, shape, opacity, color, or other attributes based on data received from the graphic tablet."},
    images: [{image:"img/input/Graphics Tablet/1.jpg",name:"Koala Pad",caption:"the KoalaPad was originally designed for use by the Apple II computer, but later was available for the IBM PC compatible computer as well."},
    {image:"img/input/Graphics Tablet/2.jpg",name:"Graphics Tablet",caption:""}]

}
];
$(document).ready(() => {
    loadCards(inputLessonItems);
})